//
// Created by Alex on 11/6/22.
//

#ifndef FTCROBOTCONTROLLER_2022_SIGNALDETECTION_H
#define FTCROBOTCONTROLLER_2022_SIGNALDETECTION_H


class signalDetection {

};


#endif //FTCROBOTCONTROLLER_2022_SIGNALDETECTION_H
